const menuItems = [
    {
        id: 1,
        title: 'Blueberry-Banana-Nut Smoothie ',
        category: 'breakfast',
        price: 560,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/blueberry-banana-nut-smoothie-1608662718.jpg?crop=0.571xw:0.571xh;0.228xw,0.263xh&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 2,
        title: 'Greek Chicken Grain Bowl',
        category: 'lunch',
        price: 400,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/greek-chicken-grain-bowl-1612542687.jpg?crop=0.6666666666666666xw:1xh;center,top&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 3,
        title: 'Classic Omelet and Greens',
        category: 'breakfast',
        price: 890,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/classic-omelet-and-greens-1608662290.jpg?crop=0.867xw:0.867xh;0.0719xw,0.0479xh&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 4,
        title: 'Egg Salad Sandwich',
        category: 'breakfast',
        price: 900,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/egg-salad-sandwich-jpg-1614890300.jpg?crop=0.891xw:1.00xh;0,0&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 5,
        title: 'Shaved Carrot and Radish Salad',
        category: 'lunch',
        price: 660,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/spring-salads-spring-carrot-salad-recipe-1580519240.png?crop=0.9984732824427481xw:1xh;center,top&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 6,
        title: 'Grilled Leek Potato Salad',
        category: 'lunch',
        price: 340,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/spring-salads-grilled-leek-potato-salad-ghk-0619-1557936651.jpg?crop=1xw:0.998780487804878xh;center,top&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 7,
        title: 'Tex-Mex Chicken Salad',
        category: 'lunch',
        price: 770,
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/tex-mex-chicken-salad-1612542751.jpg?crop=0.668xw:1.00xh;0.134xw,0&resize=980:*',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 8,
        title: 'Chocolate-Mint Bars',
        category: 'dessert',
        price: '400',
        image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2F1110se-tr-chocolate-mint-bars-x.jpg%3Fitok%3DDzjQaWrl',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 9,
        title: 'Lemon-Scented Blueberry Cupcakes',
        category: 'dessert',
        price: 560,
        image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2F1110se-tr-blueberry-cupcakes-x.jpg%3Fitok%3DzItyEnYU',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    },
    {
        id: 10,
        title: 'Bourbon-Pecan Tart with Chocolate Drizzle',
        category: 'dessert',
        price: '400',
        image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2F1110se-tr-bourbon-pecan-tart-x.jpg%3Fitok%3DkHODIEqt',
        description: 'Lorem ipsum dolor sit,t, dolor necessitatibus tenetur amet enim nihil tempora inventore nulla exercitationem eius et aperiam quidem la.',
    }
]

export default menuItems;